passing the test !
NoBetterThan97/twitter-api pull request #11
Opened 2016-10-20 13:38 UTC by Leoli0320

this version only passing the test with the vcr
haven't done with refactor, test coverage, flay

2016-10-21 01:43 UTC, cyhsutw commented
I've added test coverage reporting feature in #10, could you merge `master` in first?

2016-10-21 01:52 UTC, cyhsutw requested changes
I have re-write the code again, and commit it !

2016-10-21 01:52 UTC, cyhsutw commented on Gemfile
> +gem 'vcr'
I would like the gems being ordered alphabetically

2016-10-21 01:52 UTC, cyhsutw commented on Gemfile
> +
Please ✂️ these blank lines

2016-10-21 01:52 UTC, cyhsutw commented on config/script.rb
> +# frozen_string_literal: true
Any specific reasons placing this file under `config`?

2016-10-21 01:52 UTC, cyhsutw commented on spec/twitter/coverage/.last_run.json
> +{
Should be ignored by Git

2016-10-21 01:52 UTC, cyhsutw commented on spec/twitter/coverage/assets/0.10.0/application.css
> +/* -----------------------------------------------------------------------
Ditto, ignore this

2016-10-21 01:52 UTC, cyhsutw commented on spec/twitter/test.rb
> +# frozen_string_literal: true
What's the purpose of this file, could you provide more details please 🙏 ?

2016-10-21 01:52 UTC, cyhsutw commented on spec/twitter/tweet_spec.rb
> +require '../spec_helper.rb'
👍🤘

2016-10-21 01:57 UTC, cyhsutw commented
@Leoli0320  you might need to resolve the conflicts first, or you can close this one and do it again on another branch then open a new pull request. 

It should be much more easier to open a new pull request since I've added `simplecov` on `master` and all you need to do is stubbing requests using  `vcr` and `webmock`.

2016-10-21 02:08 UTC, Leoli0320 commented on config/script.rb
> +# frozen_string_literal: true
Haha is my test XD

2016-10-21 02:09 UTC, Leoli0320 commented on spec/twitter/coverage/.last_run.json
> +{
Ok

2016-10-21 02:11 UTC, Leoli0320 commented on spec/twitter/coverage/assets/0.10.0/application.css
> +/* -----------------------------------------------------------------------
Ok

2016-10-21 02:13 UTC, Leoli0320 commented on spec/twitter/test.rb
> +# frozen_string_literal: true
Haaaa only for my test , I will delete it. Sorry for bothering you.

2016-10-23 05:49 UTC, cyhsutw approved these changes

2016-10-23 05:57 UTC, cyhsutw commented
@edsong1257 @Leoli0320 Just for the heads up, I updated the code:

1. The names of the cassettes are now automatically generated based on the spec description and the file name of the spec.
2. Remove unused files
3. Updated README.md

### Test results:

```bash
$ bundle exec rake test
Run options: --seed 45136

# Running:

..

Finished in 0.079843s, 25.0491 runs/s, 25.0491 assertions/s.

2 runs, 2 assertions, 0 failures, 0 errors, 0 skips
Coverage report generated for RSpec to /Users/cyhsutw/Projects/temp/twitter-api/coverage. 34 / 34 LOC (100.0%) covered.
```

### Quality metrics

```bash
$ bundle exec rake quality
bundle exec rubocop lib
Inspecting 2 files
..

2 files inspected, no offenses detected
bundle exec flay lib
Total score (lower is better) = 0
bundle exec flog lib
    23.7: flog total
     3.0: flog/method average

     7.3: Twitter::Client#search_tweets    lib/twitter/client.rb:15
     5.2: Twitter::Tweet#initialize        lib/twitter/tweet.rb:6
     3.6: Twitter::Tweet::search           lib/twitter/tweet.rb:12
```

If there's no further problems, I think it's ready to go. 
Please merge if you'd like to.

2016-10-23 05:58 UTC, cyhsutw commented on spec/spec_helper.rb
> +def cassette_name(path_to_spec, description)
So here's the method that generates the names of the cassettes.

2016-10-23 12:27 UTC, cyhsutw commented on spec/twitter/tweet_spec.rb
> +VCR.configure do |c|
這個在 `spec_helper.rb` 已經設定過一次了，應該不用再設定了

2016-10-23 14:38 UTC, merged