the second version
NoBetterThan97/twitter-api pull request #3
Opened 2016-10-15 17:47 UTC by Leoli0320

這是修改後的 麻煩大家在幫我看一下啦

2016-10-16 11:46 UTC, cyhsutw requested changes
一些小建議，改完應該就差不多了

2016-10-16 11:46 UTC, cyhsutw commented on lib/twitter_lib.rb
> +    attr_reader :default_header
我覺得這個應該也不用，你們覺得呢？

2016-10-16 11:46 UTC, cyhsutw commented on lib/twitter_lib.rb
> +  def initialize(api_key:, api_secrte:)
Typo:
```diff
- api_secrte
+ api_secret
```

2016-10-16 15:05 UTC, ajay830320 commented on lib/twitter_lib.rb
> +  def initialize(api_key:, api_secrte:)
haha

2016-10-16 15:05 UTC, ajay830320 commented on lib/twitter_lib.rb
> +    attr_reader :default_header
好的!

2016-10-17 00:45 UTC, cyhsutw approved these changes

2016-10-17 00:46 UTC, cyhsutw commented
Just for the heads up, I made several changes about coding styles.

/cc @Leoli0320

2016-10-17 00:46 UTC, merged