Test_version1
NoBetterThan97/twitter-api pull request #4
Opened 2016-10-16 08:39 UTC by edsong1257

2016-10-16 12:07 UTC, cyhsutw requested changes

2016-10-16 12:07 UTC, cyhsutw commented on Gemfile
> +gem 'simplecov'
這邊有用到 `rake`、`vcr`、`webmock`、`simplecov` 嗎？

2016-10-16 12:07 UTC, cyhsutw commented on spec/twitter_api_spec.rb
> +  last_response = HTTParty.get('https://api.twitter.com/1.1/search/tweets.json',
這裡好像沒有測試到 `Twitter::Client` 的功能。

2016-10-16 12:07 UTC, cyhsutw commented on spec/twitter_api_spec.rb
> +  last_response = HTTParty.get('https://api.twitter.com/1.1/search/tweets.json',
Indentation should be one step deeper here

2016-10-16 14:28 UTC, edsong1257 commented
version 2

2016-10-17 01:06 UTC, cyhsutw approved these changes

2016-10-17 01:06 UTC, merged